import { useEffect, useState } from 'react'
import { NavLink, Navigate, Route, Routes, useNavigate } from 'react-router-dom'
import { ArrowLeft, ArrowRight, Bot, CarFront, Check, CheckCircle2, ChevronRight, CircleAlert, Clock3, Compass, FileText, Languages, MapPin, ReceiptText, RotateCcw, ShieldCheck, Sparkles, X } from 'lucide-react'
import { useApp } from './state/AppContext'
import { assistantChat, explainChallanDispute, explainOutcome, generateChecklist, generateRCChecklist, getMockChallan, getMockRC, routeService } from './api'
import en from './locales/en.json'
import hi from './locales/hi.json'

const vehicleLabel = (value) => value === 'two-wheeler' ? 'two-wheeler' : 'four-wheeler'
const steps = ['Details', 'Checklist', 'Slot', 'Apply', 'Result']

function Header() { const { savedAt, reset, locale, setLocale, profile } = useApp(); const copy = locale === 'hi' ? hi : en; return <header className="app-header"><NavLink to="/" className="brand"><span className="brand-mark">प</span><span>Parivahan <b>Sahayak</b></span></NavLink><div className="header-actions">{profile.name && <span className="profile-chip" title={profile.name}><b>{profile.name.trim().slice(0, 1).toUpperCase()}</b><span>{profile.name.trim().split(' ')[0]}</span></span>}<span className="saved-pill"><Check size={14}/>{savedAt ? copy.saved : 'Saving…'}</span><div className="language-select"><Languages size={16}/><select aria-label={copy.language} value={locale} onChange={e => setLocale(e.target.value)}><option value="en">EN</option><option value="hi">हिं</option></select></div><button className="icon-button" onClick={reset} title={copy.startOver}><RotateCcw size={18}/></button></div></header> }
function Footer() { const { locale } = useApp(); const copy = locale === 'hi' ? hi : en; return <footer className="prototype-footer"><ShieldCheck size={17}/><span><b>{copy.notice}</b> <NavLink to="/about">Learn what’s real vs mocked.</NavLink></span></footer> }
function Layout({ children, compact = false }) { return <><Header/><main className={compact ? 'page page-compact' : 'page'}>{children}</main><ChatLauncher/><Footer/></> }
function Stepper({ current }) { return <div className="stepper">{steps.map((label, index) => <div className={`step ${index <= current ? 'active' : ''}`} key={label}><span>{index < current ? <Check size={14}/> : index + 1}</span><small>{label}</small></div>)}</div> }
function Flow({ current, children }) { return <Layout compact><Stepper current={current}/><div className="flow-card">{children}</div></Layout> }
function Next({ to, children = 'Continue' }) { return <NavLink className="primary-button" to={to}>{children}<ArrowRight size={19}/></NavLink> }
function Back({ to = '/' }) { return <NavLink className="back-link" to={to}><ArrowLeft size={18}/>Back</NavLink> }
function ValidLabel({ valid, children }) { return <span className="field-label">{children}{valid && <CheckCircle2 size={16}/>}</span> }
function Skeleton({ lines = 3 }) { return <div className="skeleton-wrap">{Array.from({ length: lines }, (_, i) => <span className="skeleton" key={i}/>)}</div> }
function AIError({ retry, error }) { return <div className="ai-error"><CircleAlert size={19}/><div><b>Sahayak is having trouble right now.</b><p>Please try again in a moment. {error?.includes('GROQ_API_KEY') ? 'The server AI key needs to be configured.' : ''}</p></div>{retry && <button onClick={retry}>Try again</button>}</div> }
function MessageTime({ timestamp }) { return timestamp ? <time className="message-time" dateTime={new Date(timestamp).toISOString()}>{new Intl.DateTimeFormat(undefined, { hour: 'numeric', minute: '2-digit' }).format(timestamp)}</time> : null }
function AssistantMessage({ children, timestamp }) { return <div className="assistant-message"><span className="assistant-avatar"><Sparkles size={15}/></span><div><small>Sahayak <MessageTime timestamp={timestamp}/></small><p>{children}</p></div></div> }

function Home() { const { locale } = useApp(); const navigate = useNavigate(); const [prompt, setPrompt] = useState(''); const [routing, setRouting] = useState(false); const [routeError, setRouteError] = useState(''); const go = async (e) => { e.preventDefault(); if (!prompt.trim()) return; setRouting(true); setRouteError(''); try { const result = await routeService(prompt, locale); const paths = { driving_licence: '/dl/profile', rc_ownership: '/rc', echallan: '/challan', assistant: '/assistant' }; navigate(paths[result.service] || '/assistant') } catch (error) { setRouteError('Sahayak could not route this just now. Try again in a moment.') } finally { setRouting(false) } }; return <Layout><section className="hero"><div><p className="eyebrow">Made for every citizen</p><h1>Transport services,<br/><em>made simple.</em></h1><p>Clear next steps for driving licences, vehicle ownership and e-challans — explained in plain language.</p></div><div className="hero-orb"><Compass size={48}/><span>Your guide</span></div></section><section className="route-box"><div className="route-icon"><Sparkles size={20}/></div><div><b>Not sure where to start?</b><span>Tell Sahayak what happened in your own words.</span></div><form onSubmit={go}><input value={prompt} onChange={e => setPrompt(e.target.value)} placeholder="e.g. I got a challan for a car I sold"/><button disabled={routing} aria-label="Ask Sahayak">{routing ? <Typing/> : <ArrowRight size={20}/>}</button></form>{routeError && <p className="route-error">{routeError}</p>}</section><section><div className="section-heading"><div><p className="eyebrow">Choose a service</p><h2>How can we help today?</h2></div><span className="section-count">04 services</span></div><div className="service-grid"><ServiceCard icon={<CarFront/>} color="saffron" title="Driving Licence" description="Apply, prepare and track your licence journey." action={() => navigate('/dl/profile')} ready/><ServiceCard icon={<FileText/>} color="teal" title="Vehicle RC & Ownership" description="Check RC status or understand ownership transfer." action={() => navigate('/rc')} ready/><ServiceCard icon={<ReceiptText/>} color="rose" title="E-Challan" description="Understand a challan or prepare a dispute." action={() => navigate('/challan')} ready/><ServiceCard icon={<Bot/>} color="violet" title="Ask Sahayak" description="Get help in English or Hindi, any time." action={() => navigate('/assistant')} ready/></div></section><section className="trust-strip"><Trust icon={<ShieldCheck/>} title="Private by design" text="No sensitive identity or payment details."/><Trust icon={<Clock3/>} title="Saved on your device" text="Pick up where you left off."/><Trust icon={<Sparkles/>} title="AI-guided" text="Context-aware, plain-language help."/></section></Layout> }
function Trust({ icon, title, text }) { return <div>{icon}<span><b>{title}</b><small>{text}</small></span></div> }
function ServiceCard({ icon, color, title, description, action, ready }) { return <button className={`service-card ${color}`} onClick={action || (() => {})}><span className="service-icon">{icon}</span><div><h3>{title}</h3><p>{description}</p></div><span className="service-action">{ready ? <>Start <ChevronRight size={17}/></> : 'Next up'}</span></button> }

function DLProfile() { const { profile, updateProfile, locale } = useApp(); const ageValid = Number(profile.age) >= 18 && Number(profile.age) <= 100; const valid = profile.name.trim() && ageValid && profile.state && profile.city; const copy = locale === 'hi' ? hi : en; return <Flow current={0}><Back/><p className="eyebrow">Driving Licence · Step 1 of 5</p><h1>Let’s tailor your journey.</h1><p className="intro">A few details help Sahayak prepare the right mock checklist for you.</p><div className="form-section"><label><ValidLabel valid={profile.name.trim().length > 1}>Your full name</ValidLabel><input value={profile.name} onChange={e => updateProfile({ name: e.target.value })} placeholder="e.g. Priya Sharma"/></label><div className="two-fields"><label><ValidLabel valid={ageValid}>Age</ValidLabel><input type="number" min="18" max="100" value={profile.age} onChange={e => updateProfile({ age: e.target.value })} placeholder="18–100"/>{profile.age && !ageValid && <small className="inline-error">{copy.ageInvalid}</small>}</label><label><ValidLabel valid={Boolean(profile.state)}>State</ValidLabel><select value={profile.state} onChange={e => updateProfile({ state: e.target.value })}><option value="">Choose state</option><option>Maharashtra</option><option>Delhi</option><option>Karnataka</option><option>Tamil Nadu</option></select></label></div><label><ValidLabel valid={profile.city.trim().length > 1}>City</ValidLabel><input value={profile.city} onChange={e => updateProfile({ city: e.target.value })} placeholder="e.g. Pune"/></label></div><p className="choice-label">Which vehicle are you applying for?</p><div className="tile-row"><Choice active={profile.vehicle === 'two-wheeler'} onClick={() => updateProfile({ vehicle: 'two-wheeler' })} icon="🏍️" label="Two-wheeler"/><Choice active={profile.vehicle === 'four-wheeler'} onClick={() => updateProfile({ vehicle: 'four-wheeler' })} icon="🚗" label="Four-wheeler"/></div><p className="choice-label">Where are you in the process?</p><div className="tile-row"><Choice active={profile.journey === 'fresh'} onClick={() => updateProfile({ journey: 'fresh' })} label="Starting fresh"/><Choice active={profile.journey === 'has-ll'} onClick={() => updateProfile({ journey: 'has-ll' })} label="I have a Learner’s Licence"/></div>{valid ? <Next to="/dl/checklist">Create my checklist</Next> : <p className="validation-hint"><CircleAlert size={16}/> Complete the highlighted details to continue.</p>}</Flow> }
function Choice({ active, onClick, icon, label }) { return <button className={`choice-tile ${active ? 'selected' : ''}`} onClick={onClick}>{icon && <span>{icon}</span>}<b>{label}</b>{active && <CheckCircle2 size={18}/>}</button> }
function ChecklistCard({ title, items, storageKey = title }) { const key = `parivahan-sahayak-checklist:${storageKey}`; const [checked, setChecked] = useState(() => { try { return JSON.parse(localStorage.getItem(key)) || {} } catch { return {} } }); const toggle = (id) => setChecked(previous => { const next = { ...previous, [id]: !previous[id] }; localStorage.setItem(key, JSON.stringify(next)); return next }); const completed = items.filter(item => checked[item.id]).length; return <section className="checklist-card" aria-label={title}><div className="checklist-card-head"><div><small>INTERACTIVE CHECKLIST</small><h2>{title}</h2></div><span>{completed}/{items.length}</span></div><div className="checklist">{items.map(item => <label className={`checklist-item ${checked[item.id] ? 'checked' : ''}`} key={item.id}><input type="checkbox" checked={Boolean(checked[item.id])} onChange={() => toggle(item.id)}/><span className="checkbox-mark"><Check size={14}/></span><span><b>{item.label}</b><small>{item.note}</small></span></label>)}</div></section> }
function DLChecklist() { const { profile, locale } = useApp(); const [result, setResult] = useState(null); const [error, setError] = useState(''); const load = () => { setError(''); setResult(null); generateChecklist(profile, locale).then(setResult).catch(e => setError(e.message)) }; useEffect(load, [profile.name, profile.age, profile.state, profile.city, profile.vehicle, profile.journey, locale]); return <Flow current={1}><Back to="/dl/profile"/><p className="eyebrow">Driving Licence · Step 2 of 5</p><h1>Your personal checklist.</h1><p className="intro">Built around your saved journey details and clearly marked synthetic data.</p>{!result && !error && <><Skeleton lines={1}/><div className="checklist-skeleton"><Skeleton lines={4}/></div></>}{error && <AIError error={error} retry={load}/>} {result && <><AssistantMessage>{result.message}</AssistantMessage><ChecklistCard title={result.title} items={result.checklist} storageKey={`dl-${profile.state}-${profile.vehicle}-${profile.journey}`}/><Next to="/dl/slots">Find a practice slot</Next></>}</Flow> }
function DLSlots() { const { profile, updateProfile } = useApp(); const slots = ['Monday · 6:15 AM', 'Wednesday · 10:30 AM', 'Friday · 2:00 PM']; return <Flow current={2}><Back to="/dl/checklist"/><p className="eyebrow">Driving Licence · Step 3 of 5</p><h1>Pick your best window.</h1><p className="intro">This is a typical availability pattern, not live RTO data.</p><AssistantMessage>For {profile.city || 'your selected city'}, mock patterns suggest checking early. Choose a practice slot to continue.</AssistantMessage><div className="availability-card"><div><MapPin size={18}/><span>{profile.city || 'Your city'} Demo RTO</span></div><div className="heatmap">{[3,1,2,4,3,1,0].map((v, i) => <span key={i} className={`heat heat-${v}`}/>)}</div><small>Lower to higher mock availability</small></div><div className="slot-list">{slots.map((slot, i) => <button onClick={() => updateProfile({ bookedSlot: slot })} className={profile.bookedSlot === slot ? 'selected' : ''} key={slot}><Clock3 size={18}/><span><b>{slot}</b><small>{i === 0 ? 'Popular practice window' : 'Mock availability'}</small></span>{profile.bookedSlot === slot && <CheckCircle2 size={19}/>}</button>)}</div><Next to="/dl/application">Continue with this slot</Next></Flow> }
function DLApplication() { const { profile, updateProfile } = useApp(); return <Flow current={3}><Back to="/dl/slots"/><p className="eyebrow">Driving Licence · Step 4 of 5</p><h1>Practice application.</h1><p className="intro">Nothing you do here is sent to a government system.</p><div className="review-card"><span>Applicant</span><b>{profile.name || 'Your name'}</b><span>Vehicle</span><b>{vehicleLabel(profile.vehicle)}</b><span>Practice slot</span><b>{profile.bookedSlot || 'Not selected'}</b></div><p className="choice-label">Demo outcome for this walkthrough</p><div className="outcome-choice"><button onClick={() => updateProfile({ demoOutcome: 'success' })} className={profile.demoOutcome === 'success' ? 'selected success' : ''}><CheckCircle2/>Success — application progresses</button><button onClick={() => updateProfile({ demoOutcome: 'failure' })} className={profile.demoOutcome === 'failure' ? 'selected fail' : ''}><CircleAlert/>Needs attention — show next step</button></div><Next to="/dl/outcome">See my outcome</Next></Flow> }
function DLOutcome() { const { profile, locale } = useApp(); const [result, setResult] = useState(null); const [error, setError] = useState(''); const success = profile.demoOutcome === 'success'; const load = () => { setError(''); setResult(null); explainOutcome(profile, locale).then(setResult).catch(e => setError(e.message)) }; useEffect(load, [profile.demoOutcome, profile.name, profile.state, profile.city, locale]); return <Flow current={4}><Back to="/dl/application"/><p className="eyebrow">Driving Licence · Step 5 of 5</p><div className={`result-banner ${success ? 'success' : 'failure'}`}>{success ? <CheckCircle2/> : <CircleAlert/>}<div><span>{success ? 'Practice application accepted' : 'Practice application needs attention'}</span><h1>{success ? 'You’re moving ahead.' : 'Here’s what to do next.'}</h1></div></div>{!result && !error && <Skeleton lines={3}/>} {error && <AIError error={error} retry={load}/>} {result && <><AssistantMessage>{result.message}</AssistantMessage><div className="next-step"><span>YOUR NEXT STEP</span><p>{result.nextStep}</p></div><Next to="/assistant">Ask Sahayak a question</Next></>}</Flow> }
function RCPage() { const { locale } = useApp(); const [tab, setTab] = useState('status'); const [registration, setRegistration] = useState(''); const [status, setStatus] = useState(null); const [type, setType] = useState('private-sale'); const [checklist, setChecklist] = useState(null); const [error, setError] = useState(''); const checkRC = async (e) => { e.preventDefault(); setError(''); setStatus(await getMockRC(registration)); }; const makeChecklist = () => { setChecklist(null); setError(''); generateRCChecklist(type, locale).then(setChecklist).catch(e => setError(e.message)) }; return <Layout compact><div className="assistant-page"><Back/><p className="eyebrow">Vehicle RC & Ownership</p><h1>Keep ownership clear.</h1><p className="intro">Check a synthetic RC status or get AI-guided mock transfer steps.</p><div className="module-tabs"><button className={tab === 'status' ? 'active' : ''} onClick={() => setTab('status')}>RC status</button><button className={tab === 'transfer' ? 'active' : ''} onClick={() => setTab('transfer')}>Transfer ownership</button></div>{tab === 'status' ? <div className="module-panel"><AssistantMessage>Try <b>MH12DEMO1234</b> or <b>DL01DEMO5678</b> to see synthetic RC status.</AssistantMessage><form className="lookup-form" onSubmit={checkRC}><input value={registration} onChange={e => setRegistration(e.target.value)} placeholder="Enter mock vehicle registration"/><button>Check status</button></form>{status ? <div className="status-card"><span className={status.status === 'Active' ? 'status-live' : 'status-wait'}>{status.status}</span><h3>{status.registration}</h3><p>{status.vehicle}</p><small>{status.lastUpdated}</small></div> : registration && <p className="empty-note">No synthetic RC record found. Use one of the demo numbers above.</p>}</div> : <div className="module-panel"><p className="choice-label">Why is ownership changing?</p><div className="outcome-choice"><button onClick={() => setType('private-sale')} className={type === 'private-sale' ? 'selected success' : ''}>Private sale</button><button onClick={() => setType('inherited')} className={type === 'inherited' ? 'selected success' : ''}>Inherited vehicle</button><button onClick={() => setType('gifted')} className={type === 'gifted' ? 'selected success' : ''}>Gifted vehicle</button></div><button className="primary-button" onClick={makeChecklist}>Generate transfer checklist <ArrowRight size={19}/></button>{!checklist && !error && <p className="empty-note">Select a situation and let Sahayak prepare a mock checklist.</p>}{error && <AIError error={error} retry={makeChecklist}/>} {checklist && <><AssistantMessage>{checklist.message}</AssistantMessage><ChecklistCard title={checklist.title} items={checklist.checklist} storageKey={`rc-${type}`}/></>}</div>}</div></Layout> }
function ChallanPage() { const { locale } = useApp(); const [number, setNumber] = useState(''); const [challan, setChallan] = useState(null); const [category, setCategory] = useState('wrong vehicle number'); const [guidance, setGuidance] = useState(null); const [error, setError] = useState(''); const lookup = async (e) => { e.preventDefault(); setGuidance(null); setError(''); setChallan(await getMockChallan(number)); }; const dispute = () => { setGuidance(null); setError(''); explainChallanDispute(challan.number, category, locale).then(setGuidance).catch(e => setError(e.message)) }; return <Layout compact><div className="assistant-page"><Back/><p className="eyebrow">E-Challan</p><h1>Understand a challan.</h1><p className="intro">Review synthetic challan details, then get guided mock dispute steps if something seems wrong.</p><div className="module-panel"><AssistantMessage>Try <b>CHL-DEMO-101</b> or <b>CHL-DEMO-202</b> to view a synthetic challan.</AssistantMessage><form className="lookup-form" onSubmit={lookup}><input value={number} onChange={e => setNumber(e.target.value)} placeholder="Enter mock challan number"/><button>Find challan</button></form>{number && !challan && <p className="empty-note">No synthetic challan found. Use one of the demo numbers above.</p>}{challan && <><div className="challan-card"><span>{challan.status}</span><h3>{challan.amount}</h3><p>{challan.reason}</p><small>{challan.number} · {challan.vehicle} · {challan.date}</small></div><p className="choice-label">What seems wrong?</p><select value={category} onChange={e => setCategory(e.target.value)}><option>wrong vehicle number</option><option>sold but not transferred</option><option>duplicate entry</option><option>ANPR misread</option></select><button className="primary-button" onClick={dispute}>Get dispute guidance <ArrowRight size={19}/></button>{error && <AIError error={error} retry={dispute}/>} {guidance && <><AssistantMessage>{guidance.message}</AssistantMessage><div className="evidence-card"><b>Bring together these mock evidence items</b><ul>{guidance.evidence.map(item => <li key={item}>{item}</li>)}</ul><p><b>Next:</b> {guidance.nextStep}</p></div><div className="tracked-status"><Clock3/><div><b>Mock dispute status</b><span>Guidance prepared · ready for your review</span></div></div></>}</>}</div></div></Layout> }
function Typing() { return <div className="typing"><span/><span/><span/></div> }
const createMessage = (role, content) => ({
  id: crypto.randomUUID(),
  role,
  content,
  timestamp: Date.now(),
})

function Chat({ initial = '' }) {
  const { profile, locale } = useApp()
  const [message, setMessage] = useState(initial)
  const [messages, setMessages] = useState(() => [createMessage('assistant', `Hi ${profile.name || 'there'}! Ask me about driving licences, RC ownership or e-challans in English or Hindi.`)])
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)
  const submit = async (event) => {
    event.preventDefault()
    const content = message.trim()
    if (!content || loading) return
    const userMessage = createMessage('user', content)
    setMessages(previous => [...previous, userMessage])
    setMessage('')
    setLoading(true)
    setError('')
    try {
      const [response] = await Promise.all([assistantChat(content, profile, locale), new Promise(resolve => setTimeout(resolve, 900))])
      setMessages(previous => [...previous, createMessage('assistant', response.message)])
    } catch (e) { setError(e.message) } finally { setLoading(false) }
  }
  return <div className="chat-panel">
    {messages.map(item => item.role === 'user'
      ? <div className="user-message" key={item.id}><p>{item.content}</p><MessageTime timestamp={item.timestamp}/></div>
      : <AssistantMessage key={item.id} timestamp={item.timestamp}>{item.content}</AssistantMessage>)}
    {loading && <div className="assistant-message"><span className="assistant-avatar"><Sparkles size={15}/></span><Typing/></div>}
    {error && <AIError error={error}/>}<form className="chat-input" onSubmit={submit}><input value={message} onChange={e => setMessage(e.target.value)} placeholder="Ask Sahayak anything…"/><button disabled={loading} aria-label="Send message"><ArrowRight size={19}/></button></form>
  </div>
}
function AssistantPage() { const { locale } = useApp(); const copy = locale === 'hi' ? hi : en; const [starter, setStarter] = useState(''); const examples = locale === 'hi' ? ['मेरे लिए कौन से दस्तावेज़ चाहिए?', 'सुबह स्लॉट कब देखना अच्छा है?', 'RC ट्रांसफर कैसे समझूं?', 'गलत चालान पर क्या करूं?'] : ['Which documents should I prepare?', 'When should I check for a morning slot?', 'How do I understand RC transfer?', 'What should I do about a wrong challan?']; return <Layout compact><div className="assistant-page"><Back/><p className="eyebrow">Your personal guide</p><h1>Ask Sahayak.</h1><p className="intro">Clear answers from your saved mock profile — in English or Hindi.</p><section className="recent-questions"><b>{copy.recentQuestions}</b><div>{examples.map(question => <button key={question} onClick={() => setStarter(question)}>{question}</button>)}</div></section><Chat key={starter || 'blank'} initial={starter}/></div></Layout> }
function ChatLauncher() { const [open, setOpen] = useState(false); return <><button className="chat-fab" onClick={() => setOpen(true)} aria-label="Open Sahayak chat"><Bot size={22}/><span>Ask Sahayak</span></button>{open && <div className="chat-modal"><div className="chat-modal-head"><span><Sparkles size={17}/> Sahayak</span><button onClick={() => setOpen(false)}><X size={19}/></button></div><Chat/></div>}</> }
function About() { return <Layout compact><div className="about-page"><Back/><p className="eyebrow">Transparency first</p><h1>About this prototype.</h1><div className="about-grid"><Info title="Hackathon prototype">Parivahan Sahayak is not an official government product. It is not connected to Sarathi, Parivahan, any RTO, or another government system.</Info><Info title="What is real">The AI reasoning experience is real: it uses the configured AI service with your synthetic journey context.</Info><Info title="What is mocked">Slots, document rules, verification, outcomes, RC status and challan information are synthetic demonstrations, not official guidance.</Info><Info title="Your privacy">Never enter Aadhaar, PAN, payment, bank or OTP details. This prototype does not need or collect them.</Info></div></div></Layout> }
function Info({ title, children }) { return <article className="info-card"><h2>{title}</h2><p>{children}</p></article> }
export default function App() { return <Routes><Route path="/" element={<Home/>}/><Route path="/dl/profile" element={<DLProfile/>}/><Route path="/dl/checklist" element={<DLChecklist/>}/><Route path="/dl/slots" element={<DLSlots/>}/><Route path="/dl/application" element={<DLApplication/>}/><Route path="/dl/outcome" element={<DLOutcome/>}/><Route path="/rc" element={<RCPage/>}/><Route path="/challan" element={<ChallanPage/>}/><Route path="/assistant" element={<AssistantPage/>}/><Route path="/about" element={<About/>}/><Route path="/checklist" element={<Navigate to="/dl/checklist" replace/>}/><Route path="/slots" element={<Navigate to="/dl/slots" replace/>}/><Route path="/application" element={<Navigate to="/dl/application" replace/>}/><Route path="/outcome" element={<Navigate to="/dl/outcome" replace/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes> }
