import { NavLink, Navigate, Route, Routes } from 'react-router-dom'
import { Bot, CheckCircle2, ChevronRight, CircleHelp, Languages, RotateCcw, ShieldCheck, Sparkles } from 'lucide-react'
import { useApp } from './state/AppContext'

const steps = [
  { path: '/', label: 'Start' }, { path: '/checklist', label: 'Checklist' }, { path: '/slots', label: 'Slots' },
  { path: '/application', label: 'Apply' }, { path: '/outcome', label: 'Result' }, { path: '/assistant', label: 'Help' },
]

const vehicleLabel = (v) => v === 'two-wheeler' ? 'two-wheeler' : 'four-wheeler'

function Header() {
  const { savedAt, reset } = useApp()
  return <header className="sticky top-0 z-10 border-b border-slate-100 bg-white/95 backdrop-blur">
    <div className="mx-auto flex max-w-3xl items-center justify-between px-4 py-3">
      <NavLink to="/" className="flex items-center gap-2 font-bold text-ink"><span className="grid h-8 w-8 place-items-center rounded-lg bg-saffron text-white">प</span><span>Parivahan<br/><small className="font-medium text-slate-500">Sahayak</small></span></NavLink>
      <div className="flex items-center gap-2"><span className="hidden items-center gap-1 text-xs font-medium text-emerald-700 sm:flex"><CheckCircle2 size={15}/> {savedAt ? 'Saved ✓' : 'Not saved'}</span><NavLink to="/assistant" title="Ask the assistant" className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><Bot size={20}/></NavLink><button title="English / Hindi (Phase 4)" className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><Languages size={20}/></button><button onClick={reset} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100" title="Start over"><RotateCcw size={19}/></button></div>
    </div>
  </header>
}

function Progress() {
  return <nav aria-label="Journey progress" className="mx-auto max-w-3xl overflow-x-auto px-4 pt-5"><div className="flex min-w-max gap-1">{steps.map((step, index) => <NavLink key={step.path} to={step.path} end={step.path === '/'} className={({isActive}) => `rounded-full px-3 py-1.5 text-xs font-semibold ${isActive ? 'bg-ink text-white' : 'bg-slate-100 text-slate-500'}`}><span className="mr-1 opacity-70">{index + 1}</span>{step.label}</NavLink>)}</div></nav>
}

function Shell({ title, eyebrow, children, next, back }) {
  return <><Header/><Progress/><main className="mx-auto min-h-[calc(100vh-170px)] max-w-3xl px-4 pb-10 pt-8"><p className="text-sm font-semibold text-saffron">{eyebrow}</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-ink">{title}</h1>{children}<div className="mt-8 flex gap-3">{back && <NavLink to={back} className="button-secondary">Back</NavLink>}{next && <NavLink to={next} className="button-primary">Continue <ChevronRight size={19}/></NavLink>}</div></main><Footer/></>
}

function Start() {
  const { profile, updateProfile } = useApp()
  const valid = profile.name.trim() && Number(profile.age) >= 18 && profile.state && profile.city
  return <Shell eyebrow="Your guided journey" title="Let's get your licence journey clear."><p className="lead">Tell us a few details. We will save your progress on this device.</p><div className="form-card mt-6"><Field label="Your full name"><input value={profile.name} onChange={e => updateProfile({name:e.target.value})} placeholder="e.g. Priya Sharma" /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Age"><input type="number" min="18" value={profile.age} onChange={e => updateProfile({age:e.target.value})} placeholder="18 or older" />{profile.age && Number(profile.age) < 18 && <small className="error">You need to be 18 or older for this demo.</small>}</Field><Field label="State"><select value={profile.state} onChange={e => updateProfile({state:e.target.value})}><option value="">Select state</option><option>Maharashtra</option><option>Delhi</option><option>Karnataka</option><option>Tamil Nadu</option></select></Field></div><Field label="City"><input value={profile.city} onChange={e => updateProfile({city:e.target.value})} placeholder="e.g. Pune" /></Field><Field label="Vehicle type"><div className="choice-grid">{['two-wheeler','four-wheeler'].map(v => <button key={v} onClick={() => updateProfile({vehicle:v})} className={profile.vehicle === v ? 'selected' : ''}>{v === 'two-wheeler' ? '🏍️ Two-wheeler' : '🚗 Four-wheeler'}</button>)}</div></Field><Field label="Where are you starting?"><div className="choice-grid">{[['fresh','I am starting fresh'],['has-ll','I already have a Learner’s Licence']].map(([value,label]) => <button key={value} onClick={() => updateProfile({journey:value})} className={profile.journey === value ? 'selected' : ''}>{label}</button>)}</div></Field></div>{valid ? <NavLink to="/checklist" className="button-primary mt-6">Create my checklist <ChevronRight size={19}/></NavLink> : <p className="mt-5 text-sm text-slate-500">Complete your name, age (18+), state and city to continue.</p>}</Shell>
}
function Field({ label, children }) { return <label className="block text-sm font-semibold text-slate-700">{label}<div className="mt-2">{children}</div></label> }

function Checklist() { const { profile } = useApp(); const isLL = profile.journey === 'fresh'; return <Shell eyebrow="Step 2 of 6" title="Your personal checklist" back="/" next="/slots"><p className="lead">Placeholder guidance for {profile.name || 'you'} in {profile.city || 'your city'}. AI-powered recommendations arrive in Phase 3.</p><AssistantBubble>Based on your profile, start with your identity and address documents. {isLL ? 'You will need a Learner’s Licence before applying for a Driving Licence.' : 'Keep your existing Learner’s Licence ready.'}</AssistantBubble><ChecklistItem done="Profile details saved"/><ChecklistItem text="Keep proof of identity and current address ready"/><ChecklistItem text={`Apply for a ${vehicleLabel(profile.vehicle)} ${isLL ? 'Learner’s Licence' : 'Driving Licence'}`}/><ChecklistItem text="Choose a mock test slot"/></Shell> }
function ChecklistItem({ done, text }) { return <div className="check-item"><CheckCircle2 size={20} className={done ? 'text-emerald-600' : 'text-slate-300'}/><span>{done || text}</span></div> }

function Slots() { const { profile, updateProfile } = useApp(); const slots = ['Monday · 6:15 AM', 'Wednesday · 10:30 AM', 'Friday · 2:00 PM']; return <Shell eyebrow="Step 3 of 6" title="Find your best window" back="/checklist" next="/application"><p className="lead">Synthetic availability pattern for {profile.city || 'your selected'} RTO. This is not live government data.</p><AssistantBubble>Typical slots may open early in the morning. For this Phase 1 demo, choose any available practice slot below.</AssistantBubble><div className="slot-grid">{slots.map((slot,i) => <button key={slot} onClick={() => updateProfile({bookedSlot:slot})} className={`slot ${profile.bookedSlot === slot ? 'selected' : ''}`}><span className="font-bold">{slot}</span><small>{i === 0 ? 'Usually high demand' : 'Mock availability'}</small></button>)}</div></Shell> }

function Application() { const { profile, updateProfile } = useApp(); return <Shell eyebrow="Step 4 of 6" title="Practice application" back="/slots" next="/outcome"><p className="lead">This simulates a simple licence test or application. Nothing is submitted anywhere.</p><div className="form-card mt-6"><p className="font-semibold text-ink">Demo outcome control</p><p className="mt-1 text-sm text-slate-500">Choose an outcome so your presentation has a predictable result.</p><div className="choice-grid mt-4">{[['success','Success — application progresses'],['failure','Failure — show next-step guidance']].map(([value,label]) => <button key={value} onClick={() => updateProfile({demoOutcome:value})} className={profile.demoOutcome === value ? 'selected' : ''}>{label}</button>)}</div><div className="mt-6 rounded-xl bg-mist p-4 text-sm text-slate-600">Applicant: <b>{profile.name || 'Not entered'}</b><br/>Practice slot: <b>{profile.bookedSlot || 'Not selected'}</b></div></div></Shell> }

function Outcome() { const { profile } = useApp(); const success = profile.demoOutcome === 'success'; return <Shell eyebrow="Step 5 of 6" title={success ? 'Your application is moving ahead.' : 'Here is what to do next.'} back="/application" next="/assistant"><div className={`outcome ${success ? 'success' : 'failure'}`}>{success ? <CheckCircle2 size={31}/> : <CircleHelp size={31}/>}<div><strong>{success ? 'Mock success outcome' : 'Mock document mismatch outcome'}</strong><p>{success ? 'Your practice submission was accepted. In a real journey, the next status would be shared by the official system.' : 'The demo address proof does not match the address entered in the application. Check both documents before trying again.'}</p></div></div><AssistantBubble>{success ? 'Next, watch for your mock dispatch status. This placeholder will become an AI-generated timeline in Phase 3.' : 'Next step: use an address document with the same spelling and address as your application, then re-submit. This will become AI-generated in Phase 3.'}</AssistantBubble></Shell> }

function Assistant() { const { profile } = useApp(); return <Shell eyebrow="Step 6 of 6" title="Ask Parivahan Sahayak" back="/outcome"><p className="lead">A persistent assistant will be available across every screen in Phase 3.</p><div className="form-card mt-6"><AssistantBubble>Hi {profile.name || 'there'}! I can see you are applying for a {vehicleLabel(profile.vehicle)} licence in {profile.city || 'your city'}. Ask a question below.</AssistantBubble><input placeholder="e.g. मेरा स्लॉट कब खुलेगा?" disabled/><button className="button-disabled mt-3" disabled><Bot size={18}/> Assistant coming in Phase 3</button></div></Shell> }
function AssistantBubble({ children }) { return <div className="assistant-bubble"><Sparkles size={18}/><p>{children}</p></div> }
function Footer() { return <footer className="border-t border-slate-200 bg-slate-50 px-4 py-5 text-center text-xs leading-5 text-slate-500"><ShieldCheck className="mx-auto mb-1 text-saffron" size={18}/><b>Prototype notice:</b> This Phase 1 hackathon demo is not an official government product. No Aadhaar, PAN, payment, or OTP data is requested. Government integration and all data shown are placeholders.</footer> }

export default function App() { return <Routes><Route path="/" element={<Start/>}/><Route path="/checklist" element={<Checklist/>}/><Route path="/slots" element={<Slots/>}/><Route path="/application" element={<Application/>}/><Route path="/outcome" element={<Outcome/>}/><Route path="/assistant" element={<Assistant/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes> }
